Add Coverage rapport form Jest
icapps/nodejs-express-template pull request #7
Opened 2017-06-29 13:59 UTC by vademo

NEB-16
with the command 'yarn test' there will be an build of the code and a
test which will generate an coverage rapport
also added some files to .gitignore

2017-06-29 17:59 UTC, hoetmaaiers requested changes

2017-06-29 17:59 UTC, hoetmaaiers commented on .gitignore
> +# OS generated files #
Just something small, but a newline above would make it more consistent with the general file structure.

What is the idea behind `+# #########V#############` is this a divider thingy?

2017-06-30 06:39 UTC, vademo commented on .gitignore
> +# OS generated files #
This is a lazy copy-paste thingy 😮 will fix it

2017-06-30 09:25 UTC, hoetmaaiers approved these changes

2017-07-02 15:45 UTC, samover approved these changes

2017-07-02 15:46 UTC, merged